from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
load_dotenv()

#what is straming and why we use it?
#Streaming is a technique that allows you to receive and process data in real-time as it is
# generated by the language model. Instead of waiting for the entire response to be generated 
# before receiving it, streaming allows you to receive chunks of the response as they are produced. This can be particularly useful for long responses or when you want to provide a more interactive experience.
llm=ChatOpenAI(model="gpt-3.5-turbo", temperature=0.9,streaming=True)

response=llm.stream("What Ai and GenAi?")

for chunk in response:
    print(chunk.content, end="")
